databases:
  - name: alphablog
    databaseName: alphablog
    user: rodrigolj

services:
  - type: web
    name: Alpha-Blog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alphablog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
